id: P009214
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:28:22.795316
source_metadata:
  id: bdr:W1KG4453
  title: རྡོ་བསམ་བློ་བཟང་བསྟན་འཛིན་གྱི་གསུང་པོད་རྡོ་རྗེ་འཇིགས་བྱེད་ཀྱི་སྐོར
  author: ''
  volumes:
    6fe716a5cf944e92b5513dd49619f0b7:
      image_group_id: I1KG4567
      title: ''
      volume_number: 1
      total_pages: 368
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
