id: IC1C566DC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T04:36:36+00:00'
last_modified: '2022-06-08T09:25:54.394922+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4453
  title: རྡོ་བསམ་བློ་བཟང་བསྟན་འཛིན་གྱི་གསུང་པོད་རྡོ་རྗེ་འཇིགས་བྱེད་ཀྱི་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1904':
      image_group_id: I1KG4567
      title: ''
      total_pages: 368
      order: 1
      base_file: 1904.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
